config/routes.rb
Mml::Application.routes.draw do
  get "welcome/home"
  get '/home', to: 'home#index', as: 'home'
  get '/top_books', to: 'home#top_books', as: 'top_books'

  #resources :sessions
  #get '/auth/twitter/callback', to: 'sessions#create', as: 'callback'
  #get 'auth/twitter', to: 'sessions#create', as: 'login'
  #match 'auth/:provider/callback' => 'sessions#create',:as => 'login'
  get '/auth/:provider/callback', to: 'sessions#create', as: 'login'
  get '/profile', to: 'sessions#show', as: 'show'
  match 'logout' => 'sessions#destroy'
  delete '/signout', to: 'sessions#destroy', as: 'signout'
  
  get '/user_books', to: 'books#user', as: 'user_books'
  get '/user_reviews', to: 'reviews#user', as: 'user_reviews'
  get '/reviews', to: 'reviews#all', as: 'reviews'

  post '/books/search_gbdb'
  get '/books/new_from_gbdb'
  get '/books/search_gbdb/:search_terms', to: 'books#search_gbdb', :as => 'search_gbdb'
  
  resources :books do
    resources :reviews
  end

  resources :readers
  #root :to => redirect('/books')
  root :to => redirect('/home')
  

end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :reviews
  has_many :readers, through: :reviews
  
  def self.find_in_gbooks( params )
    books = GoogleBooks.search(params[:search_terms],{},params[:user_ip])
    
    return books
  end
  
  def self.get_first_in_gbooks(params)
    if params[:isbn]
      string = "isbn:#{params[:isbn]}"
    else
      string = "intitle:#{params[:title]}"
    end
    books = GoogleBooks.search(string,{:count => 1},params[:user_ip])
    first_gbook = books.first    
    book = {"title"=>first_gbook.title, "author"=>first_gbook.authors, "summary"=>first_gbook.description, "image_link"=>first_gbook.image_link}

    return book
  end
  
  def self.getTopBooks 
    Book.connection.select_all("SELECT books.*, avg(reviews.stars) as avg_rating
      FROM books 
      INNER JOIN reviews ON books.id = reviews.book_id 
      group by books.id, reviews.stars
      ORDER BY avg(reviews.stars) desc
      LIMIT 10")
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  
  def user
    @books = @current_reader.books
  end
  
  def show
    id = params[:id] # retrieve book ID from URI route
    @book = Book.find(id) # look up book by unique ID
    params[:user_ip] = request.remote_ip
    params[:title] = @book.title
    @gbook = Book.get_first_in_gbooks(params)
    
    # will render app/views/books/show.html.haml by default
  end
  
  def new
    # default: render 'new' template
  end

  def new_from_gbdb
    params[:user_ip] = request.remote_ip
    @gbook = Book.get_first_in_gbooks(params)
    @book = Book.create({"title"=>@gbook["title"], "author"=>@gbook["author"], "summary"=>@gbook["summary"]})
    flash[:notice] = "#{@book.title} was successfully added."
  end
  
  def create
    @book = Book.create!(params[:book])
    flash[:notice] = "#{@book.title} was successfully created."
    redirect_to books_path
  end
  
  def search_gbdb
    params[:user_ip] = request.remote_ip
    @books = Book.find_in_gbooks(params)    
    if @books.first == nil
      flash[:warning] = "'#{params[:search_terms]}' was not found in GoogleBooks."
      redirect_to books_path
    end
    if @books.total_items == 1
      book = @books.first
      #redirect_to new_from_gbdb(:title => book.title, :isbn => book.isbn)
      #redirect_to new_from_gbdb
      params = {:title => book.title, :isbn => book.isbn}
      redirect_to :action => 'new_from_gbdb', :params => params
    end
  end
  
  def destroy
    id = params[:id] # retrieve book ID from URI route
    @book = Book.find(id) # look up book by unique ID
    #if @book.readers > 1
    
    title = @book.title;
    @book.destroy;
    flash[:notice] = "#{title} was successfully deleted."
    redirect_to books_path
  end
end

app/views/books/index.html.haml
-#  This file is app/views/movies/index.html.haml
.wrapper
  %h2 All Books
   
  %table#books{:class => "table_results"}
    %thead
      %tr
        %th Book Title
        %th Book Author
        %th More Info
    %tfoot
      %tr
        %td{:class => "crud_links", :colspan => 3}= link_to "Add New Book", new_book_path
      %tr
        %td{:class => "crud_links", :colspan => 3}
          = form_tag :action => 'search_gbdb' do          
            %label{:for => 'search_terms'} Add from GoogleBook
            = text_field_tag 'search_terms'
            = submit_tag 'Search'
    %tbody
      - @books.each do |book|
        %tr
          %td= book.title
          %td= book.author
          %td= link_to "More about #{book.title}", book_path(book) 
  

app/views/books/new.html.haml
%h1 Add New Book
.wrapper
  = form_tag(books_path, {:class => 'form_book'})  do

    = label :book, :title, 'Title'
    = text_field :book, 'title'
    %br
    
    = label :book, :author, 'Author'
    = text_field :book, 'author'
    %br
    
    = label :book, :description, 'Summary'
    = text_area :book, 'summary'
    %br
    
    = submit_tag 'Save Changes'

app/views/books/new_from_gbdb.html.haml
%h1 Add your review to this book
.wrapper
  = image_tag @gbook["image_link"]
  %h2 #{@book.title}
   
  %ul#details
    %li
      Author:
      = @book.author
   
  %h3 Summary:
   
  %p#description= @book.summary
    
  = form_tag book_reviews_path(@book) do
    %label How many stars?
    = select_tag 'review[stars]', options_for_select(1..5)
    %br
    = label :review, :comments, 'Comments'
    = text_area_tag 'review[comments]', ''
    %br
    = submit_tag 'Add review'
   
  = link_to 'Back to book list', books_path

app/views/books/search_gbdb.html.haml
.wrapper
  %h2 Search Result
   
  %table#books{:class => "table_results"}
    %thead
      %tr
        %th Book
        %th Title
        %th Author
        %th Action
    %tbody
      - @books.each do |book|
        %tr
          %td= image_tag book.image_link(:zoom => 5)
          %td= book.title
          %td= book.authors
          %td= link_to "Add", books_new_from_gbdb_path(title: book.title, isbn: book.isbn)
  

app/views/books/show.html.haml
-# in app/views/movies/show.html.haml
.wrapper
  = image_tag @gbook["image_link"]
  %h2 #{@book.title}
    
  %ul#details
    %li
      Author:
      = @book.author
   
  %h3 Summary:
   
  %p#description= @book.summary
    
  = form_tag book_reviews_path(@book) do
    %label How many stars?
    = select_tag 'review[stars]', options_for_select(1..5)
    %br
    = label :review, :comments, 'Comments'
    = text_area_tag 'review[comments]', ''
    %br
    = submit_tag 'Add review'
   
  = link_to 'Back to book list', books_path

app/views/books/user.html.haml
-#  This file is app/views/movies/index.html.haml
.wrapper
  %h2 All Your Books
   
  %table#books{:class => "table_results"}
    %thead
      %tr
        %th Book Title
        %th Book Author
        %th More Info
    %tfoot
      %tr
        %td{:class => "crud_links", :colspan => 4}= link_to "Add New Book", new_book_path
      %tr
        %td{:class => "crud_links", :colspan => 3}
          = form_tag :action => 'search_gbdb' do          
            %label{:for => 'search_terms'} Add from GoogleBook
            = text_field_tag 'search_terms'
            = submit_tag 'Search'
    %tbody
      - @books.each do |book|
        %tr
          %td= book.title
          %td= book.author
          %td= link_to "More about #{book.title}", book_path(book) 
  